package tonyfettes:torch;

world mnist {
  export load: func(blob: string);
  export save: func() -> string;
  export infer: func(input: list<f32>) -> list<f32>;
  export train: func(batch: list<tuple<list<f32>, s32>>, learning-rate: f32) -> f32;
}
