package tonyfettes:torch;

world mnist {
  export load: func(blob: string);
  export save: func() -> string;
  export infer: func(input: list<u8>) -> list<f64>;
  export train: func(batch: list<tuple<list<u8>, s32>>, learning-rate: f64) -> f64;
}
