name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pytorch:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install '.[dev]'

      - name: Run tests
        run: pytest

  coverage:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4

      - name: Install MoonBit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Update dependency index
        run: moon update

      - name: Run tests
        run: |
          moon test --enable-coverage --target=wasm
          moon test --enable-coverage --target=wasm-gc

      - name: Generate coverage reports
        run: |
          moon coverage report \
            -f cobertura       \
            -o coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
